name: Publish to GitHub Packages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: yarn Install dependencies
      run: yarn
      

    - name: Build dist
      run: npm run build

    - name: Build Docs
      run: npm run docs:build

    - name: Publish to npm registry
      run: |
        echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > ~/.npmrc
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_DATABEND_TOKEN_NPM_OUT }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.DATABEND_CLOUD_NPM_TOKEN }}
        publish_dir: ./docs-dist  # Change this to the directory you want to deploy

